### ISSUE TITLE
Wrong AppId

### ISSUE THREAD

**Issue by stavangr** [AppleEducate/app_review#1]
The method AppReview.getAppID just returns 'com.appleeducate.appreview' on Android. I haven't tested it on iOS.

**Comment by AppleEducate** [comment]
iOS is working, thanks I just saw this too on android. Working on fix now.

**Comment by AppleEducate** [comment]
@stavangr thanks for finding that! it is now fixed on the master branch. this issue must have slipped by me because I never saw the notification.

**Comment by AppleEducate** [comment]
Make sure to run.` flutter clean` then upgrade packages.

**Comment by stavangr** [comment]
Cool, thanks
