### ISSUE TITLE
Cannot use with actual Flutter Version

### ISSUE THREAD

**Issue by Robin38219733** [AppleEducate/app_review#4]
I am using Flutter Version 0.4.4 but it seems to me that app_review requires Flutter version 0.3.1.

## Output of flutter packages get in project folder:
Running "flutter packages get" in project...
The current Flutter SDK version is 0.4.4.

Because project depends on app_review from git which requires Flutter SDK version ^0.3.1, version solving failed.
pub get failed (1)

## Output of Flutter Doctor -v:
[✓] Flutter (Channel beta, v0.4.4, on Mac OS X 10.13.3 17D102, locale de-DE)
    • Flutter version 0.4.4 at /flutter
    • Framework revision f9bb4289e9 (4 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/robjan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.13.2

[✓] Connected devices (1 available)
    • iPhone 5s • XXX • ios • iOS 11.3 (simulator)

• No issues found!

**Comment by AppleEducate** [comment]
I patched this on the master branch. I am currently using it on the latest flutter. Is it working for you now?

**Comment by AppleEducate** [comment]
Closing resolved on the latest master branch.
