### ISSUE TITLE
Unsupported Swift Language Version

### ISSUE THREAD

**Issue by Panthro** [AppleEducate/app_review#5]
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.

![image](https://user-images.githubusercontent.com/1565421/46801564-4b122b00-cd5b-11e8-9bbe-5e2c164fc0ad.png)

**Comment by dmjones** [comment]
See https://stackoverflow.com/a/52194702/474189.

**Comment by AppleEducate** [comment]
Thank you for finding that: https://github.com/AppleEducate/plugins

I updated the plugin: `app_review: 0.0.9`
